[2024-06-17T17:03:23.143+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: full_dbt_execute.run_dbt manual__2024-06-17T17:03:22.026171+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
